-- MySQL Script generated by MySQL Workbench
-- 08/24/17 02:04:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema buscoPiso
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `buscoPiso` ;

-- -----------------------------------------------------
-- Schema buscoPiso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buscoPiso` DEFAULT CHARACTER SET utf8 ;
USE `buscoPiso` ;

-- -----------------------------------------------------
-- Table `buscoPiso`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`groups` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`groups` (
  `groups_id_group` INT NOT NULL AUTO_INCREMENT,
  `groups_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`groups_id_group`),
  UNIQUE INDEX `group_name_UNIQUE` (`groups_name` ASC),
  UNIQUE INDEX `groups_id_group_UNIQUE` (`groups_id_group` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`countries` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`countries` (
  `idcountries` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idcountries`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `idcountries_UNIQUE` (`idcountries` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`autonomous_communities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`autonomous_communities` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`autonomous_communities` (
  `idautonomous_communities` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `countries_idcountries` INT NOT NULL,
  PRIMARY KEY (`idautonomous_communities`, `countries_idcountries`),
  UNIQUE INDEX `idautonomous_communities_UNIQUE` (`idautonomous_communities` ASC),
  INDEX `fk_autonomous_communities_countries1_idx` (`countries_idcountries` ASC),
  CONSTRAINT `fk_autonomous_communities_countries1`
    FOREIGN KEY (`countries_idcountries`)
    REFERENCES `buscoPiso`.`countries` (`idcountries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`provinces` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`provinces` (
  `idprovinces` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `autonomous_communities_idautonomous_communities` INT NOT NULL,
  PRIMARY KEY (`idprovinces`, `autonomous_communities_idautonomous_communities`),
  INDEX `fk_provinces_autonomous_communities1_idx` (`autonomous_communities_idautonomous_communities` ASC),
  UNIQUE INDEX `idprovinces_UNIQUE` (`idprovinces` ASC),
  CONSTRAINT `fk_provinces_autonomous_communities1`
    FOREIGN KEY (`autonomous_communities_idautonomous_communities`)
    REFERENCES `buscoPiso`.`autonomous_communities` (`idautonomous_communities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`municipalities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`municipalities` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`municipalities` (
  `idmunicipalities` INT NOT NULL AUTO_INCREMENT,
  `provinces_idprovinces` INT NOT NULL,
  `municipality_code` VARCHAR(45) NOT NULL,
  `dc` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idmunicipalities`, `provinces_idprovinces`),
  UNIQUE INDEX `idmunicipalities_UNIQUE` (`idmunicipalities` ASC),
  INDEX `fk_municipalities_provinces1_idx` (`provinces_idprovinces` ASC),
  CONSTRAINT `fk_municipalities_provinces1`
    FOREIGN KEY (`provinces_idprovinces`)
    REFERENCES `buscoPiso`.`provinces` (`idprovinces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`business_office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`business_office` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`business_office` (
  `idoffice` INT NOT NULL AUTO_INCREMENT,
  `tradename` VARCHAR(250) NOT NULL,
  `logo` VARCHAR(250) NULL,
  `area_of_action` VARCHAR(250) NULL,
  `office_description` VARCHAR(1000) NULL,
  `office_foto` VARCHAR(250) NULL,
  `office_foto2` VARCHAR(250) NULL,
  `office_foto3` VARCHAR(250) NULL,
  `address` VARCHAR(250) NULL,
  `municipalities_idmunicipalities` INT NOT NULL,
  PRIMARY KEY (`idoffice`, `municipalities_idmunicipalities`),
  UNIQUE INDEX `idoffice_UNIQUE` (`idoffice` ASC),
  INDEX `fk_office_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  CONSTRAINT `fk_office_municipalities1`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`additional_features_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`additional_features_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`additional_features_users` (
  `idadditional_features_users` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NULL,
  `courses` VARCHAR(2000) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `work_position` VARCHAR(500) NULL,
  PRIMARY KEY (`idadditional_features_users`),
  UNIQUE INDEX `idcommercials_UNIQUE` (`idadditional_features_users` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`users` (
  `users_id_user` INT NOT NULL AUTO_INCREMENT,
  `users_name` VARCHAR(250) NOT NULL,
  `users_firstname` VARCHAR(250) NOT NULL,
  `users_lastname` VARCHAR(250) NULL,
  `users_email` VARCHAR(250) NOT NULL,
  `users_phone` VARCHAR(12) NULL,
  `floor_description` VARCHAR(2000) NULL,
  `state` TINYINT(1) NOT NULL,
  `last_login` TIMESTAMP NULL,
  `groups_groups_id_group` INT NOT NULL,
  `business_office_idoffice` INT NULL,
  `business_office_municipalities_idmunicipalities` INT NULL,
  `additional_features_users_idadditional_features_users` INT NULL,
  PRIMARY KEY (`users_id_user`, `groups_groups_id_group`),
  UNIQUE INDEX `users_email_UNIQUE` (`users_email` ASC),
  UNIQUE INDEX `users_phone_UNIQUE` (`users_phone` ASC),
  UNIQUE INDEX `users_id_user_UNIQUE` (`users_id_user` ASC),
  INDEX `fk_Users_Groups1_idx` (`groups_groups_id_group` ASC),
  INDEX `fk_users_business_office1_idx` (`business_office_idoffice` ASC, `business_office_municipalities_idmunicipalities` ASC),
  INDEX `fk_users_additional_features_users1_idx` (`additional_features_users_idadditional_features_users` ASC),
  CONSTRAINT `fk_Users_Groups1`
    FOREIGN KEY (`groups_groups_id_group`)
    REFERENCES `buscoPiso`.`groups` (`groups_id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_business_office1`
    FOREIGN KEY (`business_office_idoffice` , `business_office_municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`business_office` (`idoffice` , `municipalities_idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_additional_features_users1`
    FOREIGN KEY (`additional_features_users_idadditional_features_users`)
    REFERENCES `buscoPiso`.`additional_features_users` (`idadditional_features_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`road_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`road_types` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`road_types` (
  `roadType_id_roadType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roadType_id_roadType`),
  UNIQUE INDEX `roadType_name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `roadType_id_roadType_UNIQUE` (`roadType_id_roadType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`type_of_contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`type_of_contract` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`type_of_contract` (
  `idtype_of_contract` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idtype_of_contract`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`floor_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`floor_conditions` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`floor_conditions` (
  `idfloor_conditions` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfloor_conditions`),
  UNIQUE INDEX `idfloor_conditions_UNIQUE` (`idfloor_conditions` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`floors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`floors` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`floors` (
  `idfloors` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NOT NULL,
  `square_meters` INT NOT NULL,
  `bedrooms` INT NOT NULL,
  `publication_date` DATE NOT NULL,
  `address` VARCHAR(250) NULL,
  `municipalities_idmunicipalities` INT NOT NULL,
  `type_of_contract_idtype_of_contract` INT NOT NULL,
  `floor_conditions_idfloor_conditions` INT NOT NULL,
  `road_types_roadType_id_roadType` INT NOT NULL,
  PRIMARY KEY (`idfloors`, `municipalities_idmunicipalities`, `type_of_contract_idtype_of_contract`, `floor_conditions_idfloor_conditions`, `road_types_roadType_id_roadType`),
  UNIQUE INDEX `idfloors_UNIQUE` (`idfloors` ASC),
  INDEX `fk_floors_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  INDEX `fk_floors_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_floors_floor_conditions1_idx` (`floor_conditions_idfloor_conditions` ASC),
  INDEX `fk_floors_road_types1_idx` (`road_types_roadType_id_roadType` ASC),
  CONSTRAINT `fk_floors_municipalities1`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_floors_type_of_contract1`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_floors_floor_conditions1`
    FOREIGN KEY (`floor_conditions_idfloor_conditions`)
    REFERENCES `buscoPiso`.`floor_conditions` (`idfloor_conditions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_floors_road_types1`
    FOREIGN KEY (`road_types_roadType_id_roadType`)
    REFERENCES `buscoPiso`.`road_types` (`roadType_id_roadType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`floors_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`floors_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`floors_users` (
  `users_users_id_user` INT NOT NULL,
  `floors_idfloors` INT NOT NULL,
  PRIMARY KEY (`users_users_id_user`, `floors_idfloors`),
  INDEX `fk_floors_users_floors1_idx` (`floors_idfloors` ASC),
  CONSTRAINT `fk_floors_users_Users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_floors_users_floors1`
    FOREIGN KEY (`floors_idfloors`)
    REFERENCES `buscoPiso`.`floors` (`idfloors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`additional_features`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`additional_features` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`additional_features` (
  `idadditional_features` INT NOT NULL AUTO_INCREMENT,
  `air_conditioner` TINYINT(1) NOT NULL DEFAULT 0,
  `built_in_wardrobe` TINYINT(1) NOT NULL DEFAULT 0,
  `elevator` TINYINT(1) NOT NULL DEFAULT 0,
  `exterior` TINYINT(1) NOT NULL DEFAULT 0,
  `parking` TINYINT(1) NOT NULL DEFAULT 0,
  `garden` TINYINT(1) NOT NULL DEFAULT 0,
  `pool` TINYINT(1) NOT NULL DEFAULT 0,
  `storage_room` TINYINT(1) NOT NULL DEFAULT 0,
  `community_zone` TINYINT(1) NOT NULL DEFAULT 0,
  `gym` TINYINT(1) NOT NULL DEFAULT 0,
  `floors_idfloors` INT NOT NULL,
  PRIMARY KEY (`idadditional_features`, `floors_idfloors`),
  UNIQUE INDEX `idadditional_features_UNIQUE` (`idadditional_features` ASC),
  INDEX `fk_additional_features_floors1_idx` (`floors_idfloors` ASC),
  CONSTRAINT `fk_additional_features_floors1`
    FOREIGN KEY (`floors_idfloors`)
    REFERENCES `buscoPiso`.`floors` (`idfloors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`contracts` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`contracts` (
  `idcontract` INT NOT NULL AUTO_INCREMENT,
  `tradename` VARCHAR(250) NOT NULL,
  `tax_name` VARCHAR(250) NOT NULL,
  `cif_nif` VARCHAR(20) NOT NULL,
  `contact_person` VARCHAR(150) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `domicile` VARCHAR(250) NOT NULL,
  `postal_code` INT NOT NULL,
  `phone` INT NULL,
  `fax` INT NULL,
  `billing_email` VARCHAR(150) NULL,
  `billing_account_number` INT NULL,
  `business_office_idoffice` INT NOT NULL,
  PRIMARY KEY (`idcontract`),
  UNIQUE INDEX `idcompanies_UNIQUE` (`idcontract` ASC),
  INDEX `fk_contracts_business_office1_idx` (`business_office_idoffice` ASC),
  CONSTRAINT `fk_contracts_business_office1`
    FOREIGN KEY (`business_office_idoffice`)
    REFERENCES `buscoPiso`.`business_office` (`idoffice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`distribution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`distribution` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`distribution` (
  `iddistribution` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddistribution`),
  UNIQUE INDEX `iddistribution_UNIQUE` (`iddistribution` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`type_of_building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`type_of_building` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`type_of_building` (
  `idtype_of_building` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype_of_building`),
  UNIQUE INDEX `idtype_of_building_UNIQUE` (`idtype_of_building` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`office_features`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`office_features` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`office_features` (
  `idoffice_features` INT NOT NULL AUTO_INCREMENT,
  `hot_water` TINYINT(1) NOT NULL DEFAULT 0,
  `air_conditioner` TINYINT(1) NOT NULL DEFAULT 0,
  `elevator` TINYINT(1) NOT NULL DEFAULT 0,
  `heating` TINYINT(1) NOT NULL DEFAULT 0,
  `exterior` TINYINT(1) NOT NULL DEFAULT 0,
  `garage` TINYINT(1) NOT NULL DEFAULT 0,
  `security` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idoffice_features`),
  UNIQUE INDEX `idoffice_features_UNIQUE` (`idoffice_features` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`offices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`offices` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`offices` (
  `idoffices` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NOT NULL,
  `square_meters` INT NOT NULL,
  `publication_date` DATE NOT NULL,
  `address` VARCHAR(250) NULL,
  `local` TINYINT(1) NOT NULL DEFAULT 0,
  `warehouse` TINYINT(1) NOT NULL DEFAULT 0,
  `distribution_iddistribution` INT NOT NULL,
  `type_of_building_idtype_of_building` INT NOT NULL,
  `office_features_idoffice_features` INT NOT NULL,
  `municipalities_idmunicipalities` INT NOT NULL,
  `type_of_contract_idtype_of_contract` INT NOT NULL,
  `road_types_roadType_id_roadType` INT NOT NULL,
  PRIMARY KEY (`idoffices`, `distribution_iddistribution`, `type_of_building_idtype_of_building`, `office_features_idoffice_features`, `municipalities_idmunicipalities`, `type_of_contract_idtype_of_contract`, `road_types_roadType_id_roadType`),
  INDEX `fk_offices_distribution1_idx` (`distribution_iddistribution` ASC),
  INDEX `fk_offices_type_of_building1_idx` (`type_of_building_idtype_of_building` ASC),
  UNIQUE INDEX `idoffices_UNIQUE` (`idoffices` ASC),
  INDEX `fk_offices_office_features1_idx` (`office_features_idoffice_features` ASC),
  INDEX `fk_offices_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  INDEX `fk_offices_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_offices_road_types1_idx` (`road_types_roadType_id_roadType` ASC),
  CONSTRAINT `fk_offices_distribution1`
    FOREIGN KEY (`distribution_iddistribution`)
    REFERENCES `buscoPiso`.`distribution` (`iddistribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_type_of_building1`
    FOREIGN KEY (`type_of_building_idtype_of_building`)
    REFERENCES `buscoPiso`.`type_of_building` (`idtype_of_building`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_office_features1`
    FOREIGN KEY (`office_features_idoffice_features`)
    REFERENCES `buscoPiso`.`office_features` (`idoffice_features`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_municipalities1`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_type_of_contract1`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_road_types1`
    FOREIGN KEY (`road_types_roadType_id_roadType`)
    REFERENCES `buscoPiso`.`road_types` (`roadType_id_roadType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`offices_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`offices_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`offices_users` (
  `users_users_id_user` INT NOT NULL,
  `offices_idoffices` INT NOT NULL,
  PRIMARY KEY (`users_users_id_user`, `offices_idoffices`),
  INDEX `fk_offices_users_offices1_idx` (`offices_idoffices` ASC),
  CONSTRAINT `fk_offices_users_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_users_offices1`
    FOREIGN KEY (`offices_idoffices`)
    REFERENCES `buscoPiso`.`offices` (`idoffices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`location` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `mall` TINYINT(1) NOT NULL DEFAULT 0,
  `street_level` TINYINT(1) NOT NULL DEFAULT 0,
  `mezzanine` TINYINT(1) NOT NULL DEFAULT 0,
  `underground` TINYINT(1) NOT NULL DEFAULT 0,
  `others` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idlocation`),
  UNIQUE INDEX `idlocation_UNIQUE` (`idlocation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`locals_warehouses_features`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`locals_warehouses_features` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`locals_warehouses_features` (
  `idlocals_warehouses_features` INT NOT NULL AUTO_INCREMENT,
  `air_conditioner` TINYINT(1) NOT NULL DEFAULT 0,
  `heating` TINYINT(1) NOT NULL DEFAULT 0,
  `corner` TINYINT(1) NOT NULL DEFAULT 0,
  `smoke_outlet` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idlocals_warehouses_features`),
  UNIQUE INDEX `idlocals_warehouses_features_UNIQUE` (`idlocals_warehouses_features` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`locals_warehouses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`locals_warehouses` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`locals_warehouses` (
  `idlocals_warehouses` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NOT NULL,
  `square_meters` INT NOT NULL,
  `publication_date` DATE NOT NULL,
  `location_idlocation` INT NOT NULL,
  `locals_warehouses_features_idlocals_warehouses_features` INT NOT NULL,
  `municipalities_idmunicipalities` INT NOT NULL,
  `type_of_contract_idtype_of_contract` INT NOT NULL,
  `road_types_roadType_id_roadType` INT NOT NULL,
  PRIMARY KEY (`idlocals_warehouses`, `location_idlocation`, `locals_warehouses_features_idlocals_warehouses_features`, `municipalities_idmunicipalities`, `type_of_contract_idtype_of_contract`, `road_types_roadType_id_roadType`),
  INDEX `fk_locals_warehouses_location1_idx` (`location_idlocation` ASC),
  INDEX `fk_locals_warehouses_locals_warehouses_features1_idx` (`locals_warehouses_features_idlocals_warehouses_features` ASC),
  INDEX `fk_locals_warehouses_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  UNIQUE INDEX `idlocals_warehouses_UNIQUE` (`idlocals_warehouses` ASC),
  INDEX `fk_locals_warehouses_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_locals_warehouses_road_types1_idx` (`road_types_roadType_id_roadType` ASC),
  CONSTRAINT `fk_locals_warehouses_location1`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `buscoPiso`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locals_warehouses_locals_warehouses_features1`
    FOREIGN KEY (`locals_warehouses_features_idlocals_warehouses_features`)
    REFERENCES `buscoPiso`.`locals_warehouses_features` (`idlocals_warehouses_features`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locals_warehouses_municipalities1`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locals_warehouses_type_of_contract1`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locals_warehouses_road_types1`
    FOREIGN KEY (`road_types_roadType_id_roadType`)
    REFERENCES `buscoPiso`.`road_types` (`roadType_id_roadType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`garages_features`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`garages_features` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`garages_features` (
  `idgarages_features` INT NOT NULL AUTO_INCREMENT,
  `motorcycle_seat` TINYINT(1) NOT NULL DEFAULT 0,
  `automatic_door` TINYINT(1) NOT NULL DEFAULT 0,
  `security` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idgarages_features`),
  UNIQUE INDEX `idgarages_features_UNIQUE` (`idgarages_features` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`garages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`garages` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`garages` (
  `idgarages` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NOT NULL,
  `publication_date` DATE NOT NULL,
  `garages_features_idgarages_features` INT NOT NULL,
  `type_of_contract_idtype_of_contract` INT NOT NULL,
  `municipalities_idmunicipalities` INT NOT NULL,
  `road_types_roadType_id_roadType` INT NOT NULL,
  PRIMARY KEY (`idgarages`, `garages_features_idgarages_features`, `type_of_contract_idtype_of_contract`, `municipalities_idmunicipalities`, `road_types_roadType_id_roadType`),
  INDEX `fk_garages_garages_features1_idx` (`garages_features_idgarages_features` ASC),
  INDEX `fk_garages_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_garages_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  INDEX `fk_garages_road_types1_idx` (`road_types_roadType_id_roadType` ASC),
  CONSTRAINT `fk_garages_garages_features1`
    FOREIGN KEY (`garages_features_idgarages_features`)
    REFERENCES `buscoPiso`.`garages_features` (`idgarages_features`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_garages_type_of_contract1`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_garages_municipalities1`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_garages_road_types1`
    FOREIGN KEY (`road_types_roadType_id_roadType`)
    REFERENCES `buscoPiso`.`road_types` (`roadType_id_roadType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`garages_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`garages_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`garages_users` (
  `garages_idgarages` INT NOT NULL,
  `users_users_id_user` INT NOT NULL,
  PRIMARY KEY (`garages_idgarages`, `users_users_id_user`),
  INDEX `fk_garages_users_users1_idx` (`users_users_id_user` ASC),
  CONSTRAINT `fk_garages_users_garages1`
    FOREIGN KEY (`garages_idgarages`)
    REFERENCES `buscoPiso`.`garages` (`idgarages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_garages_users_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`locals_warehouses_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`locals_warehouses_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`locals_warehouses_users` (
  `locals_warehouses_idlocals_warehouses` INT NOT NULL,
  `users_users_id_user` INT NOT NULL,
  PRIMARY KEY (`locals_warehouses_idlocals_warehouses`, `users_users_id_user`),
  INDEX `fk_locals_warehouses_users_users1_idx` (`users_users_id_user` ASC),
  CONSTRAINT `fk_locals_warehouses_users_locals_warehouses1`
    FOREIGN KEY (`locals_warehouses_idlocals_warehouses`)
    REFERENCES `buscoPiso`.`locals_warehouses` (`idlocals_warehouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locals_warehouses_users_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`land_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`land_type` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`land_type` (
  `idland_type` INT NOT NULL AUTO_INCREMENT,
  `urban` TINYINT(1) NOT NULL DEFAULT 0,
  `urbanizable` TINYINT(1) NOT NULL DEFAULT 0,
  `not_urbanizable` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idland_type`),
  UNIQUE INDEX `idland_type_UNIQUE` (`idland_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`lands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`lands` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`lands` (
  `idlands` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NOT NULL,
  `square_meters` INT NOT NULL,
  `land_type_idland_type` INT NOT NULL,
  `municipalities_idmunicipalities` INT NOT NULL,
  `type_of_contract_idtype_of_contract` INT NOT NULL,
  `road_types_roadType_id_roadType` INT NOT NULL,
  PRIMARY KEY (`idlands`, `land_type_idland_type`, `municipalities_idmunicipalities`, `type_of_contract_idtype_of_contract`, `road_types_roadType_id_roadType`),
  UNIQUE INDEX `idlands_UNIQUE` (`idlands` ASC),
  INDEX `fk_lands_land_type1_idx` (`land_type_idland_type` ASC),
  INDEX `fk_lands_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  INDEX `fk_lands_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_lands_road_types1_idx` (`road_types_roadType_id_roadType` ASC),
  CONSTRAINT `fk_lands_land_type1`
    FOREIGN KEY (`land_type_idland_type`)
    REFERENCES `buscoPiso`.`land_type` (`idland_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lands_municipalities1`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lands_type_of_contract1`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lands_road_types1`
    FOREIGN KEY (`road_types_roadType_id_roadType`)
    REFERENCES `buscoPiso`.`road_types` (`roadType_id_roadType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`lands_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`lands_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`lands_users` (
  `lands_idlands` INT NOT NULL,
  `users_users_id_user` INT NOT NULL,
  PRIMARY KEY (`lands_idlands`, `users_users_id_user`),
  INDEX `fk_lands_users_users1_idx` (`users_users_id_user` ASC),
  CONSTRAINT `fk_lands_users_lands1`
    FOREIGN KEY (`lands_idlands`)
    REFERENCES `buscoPiso`.`lands` (`idlands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lands_users_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`floors_search_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`floors_search_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`floors_search_users` (
  `idfloors_search_users` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NULL,
  `square_meters` INT NULL,
  `bedrooms` INT NULL,
  `publication_date` DATE NULL,
  `municipalities_idmunicipalities` INT NULL,
  `floor_conditions_idfloor_conditions` INT NULL,
  `type_of_contract_idtype_of_contract` INT NULL,
  `users_users_id_user` INT NOT NULL,
  PRIMARY KEY (`idfloors_search_users`, `users_users_id_user`),
  INDEX `fk_floors_search_users_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  INDEX `fk_floors_search_users_floor_conditions1_idx` (`floor_conditions_idfloor_conditions` ASC),
  INDEX `fk_floors_search_users_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_floors_search_users_users1_idx` (`users_users_id_user` ASC),
  CONSTRAINT `fk_floors_search_users_municipalities1`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_floors_search_users_floor_conditions1`
    FOREIGN KEY (`floor_conditions_idfloor_conditions`)
    REFERENCES `buscoPiso`.`floor_conditions` (`idfloor_conditions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_floors_search_users_type_of_contract1`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_floors_search_users_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`offices_search_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`offices_search_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`offices_search_users` (
  `idoffices_search_users` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NULL,
  `square_meters` INT NULL,
  `publication_date` DATE NULL,
  `address` VARCHAR(250) NULL,
  `local` TINYINT(1) NULL DEFAULT 0,
  `warehouse` TINYINT(1) NULL DEFAULT 0,
  `distribution_iddistribution` INT NULL,
  `type_of_building_idtype_of_building` INT NULL,
  `office_features_idoffice_features` INT NULL,
  `municipalities_idmunicipalities` INT NULL,
  `type_of_contract_idtype_of_contract` INT NULL,
  `users_users_id_user` INT NOT NULL,
  PRIMARY KEY (`idoffices_search_users`, `users_users_id_user`),
  INDEX `fk_offices_distribution1_idx` (`distribution_iddistribution` ASC),
  INDEX `fk_offices_type_of_building1_idx` (`type_of_building_idtype_of_building` ASC),
  UNIQUE INDEX `idoffices_UNIQUE` (`idoffices_search_users` ASC),
  INDEX `fk_offices_office_features1_idx` (`office_features_idoffice_features` ASC),
  INDEX `fk_offices_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  INDEX `fk_offices_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_offices_search_users_users1_idx` (`users_users_id_user` ASC),
  CONSTRAINT `fk_offices_distribution10`
    FOREIGN KEY (`distribution_iddistribution`)
    REFERENCES `buscoPiso`.`distribution` (`iddistribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_type_of_building10`
    FOREIGN KEY (`type_of_building_idtype_of_building`)
    REFERENCES `buscoPiso`.`type_of_building` (`idtype_of_building`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_office_features10`
    FOREIGN KEY (`office_features_idoffice_features`)
    REFERENCES `buscoPiso`.`office_features` (`idoffice_features`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_municipalities10`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_type_of_contract10`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offices_search_users_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`garages_search_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`garages_search_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`garages_search_users` (
  `idgarages` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NULL,
  `publication_date` DATE NULL,
  `garages_features_idgarages_features` INT NULL,
  `type_of_contract_idtype_of_contract` INT NULL,
  `municipalities_idmunicipalities` INT NULL,
  `users_users_id_user` INT NOT NULL,
  PRIMARY KEY (`idgarages`, `users_users_id_user`),
  INDEX `fk_garages_garages_features1_idx` (`garages_features_idgarages_features` ASC),
  INDEX `fk_garages_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_garages_search_users_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  INDEX `fk_garages_search_users_users1_idx` (`users_users_id_user` ASC),
  CONSTRAINT `fk_garages_garages_features10`
    FOREIGN KEY (`garages_features_idgarages_features`)
    REFERENCES `buscoPiso`.`garages_features` (`idgarages_features`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_garages_type_of_contract10`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_garages_search_users_municipalities1`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_garages_search_users_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`locals_warehouses_search_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`locals_warehouses_search_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`locals_warehouses_search_users` (
  `idlocals_warehouses` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NULL,
  `square_meters` INT NULL,
  `publication_date` DATE NULL,
  `location_idlocation` INT NULL,
  `locals_warehouses_features_idlocals_warehouses_features` INT NULL,
  `municipalities_idmunicipalities` INT NULL,
  `type_of_contract_idtype_of_contract` INT NULL,
  `users_users_id_user` INT NOT NULL,
  PRIMARY KEY (`idlocals_warehouses`, `users_users_id_user`),
  INDEX `fk_locals_warehouses_location1_idx` (`location_idlocation` ASC),
  INDEX `fk_locals_warehouses_locals_warehouses_features1_idx` (`locals_warehouses_features_idlocals_warehouses_features` ASC),
  INDEX `fk_locals_warehouses_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  UNIQUE INDEX `idlocals_warehouses_UNIQUE` (`idlocals_warehouses` ASC),
  INDEX `fk_locals_warehouses_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_locals_warehouses_search_users_users1_idx` (`users_users_id_user` ASC),
  CONSTRAINT `fk_locals_warehouses_location10`
    FOREIGN KEY (`location_idlocation`)
    REFERENCES `buscoPiso`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locals_warehouses_locals_warehouses_features10`
    FOREIGN KEY (`locals_warehouses_features_idlocals_warehouses_features`)
    REFERENCES `buscoPiso`.`locals_warehouses_features` (`idlocals_warehouses_features`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locals_warehouses_municipalities10`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locals_warehouses_type_of_contract10`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locals_warehouses_search_users_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`lands_search_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`lands_search_users` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`lands_search_users` (
  `idlands` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL NOT NULL,
  `square_meters` INT NOT NULL,
  `land_type_idland_type` INT NOT NULL,
  `municipalities_idmunicipalities` INT NOT NULL,
  `type_of_contract_idtype_of_contract` INT NOT NULL,
  `users_users_id_user` INT NOT NULL,
  PRIMARY KEY (`idlands`, `users_users_id_user`),
  UNIQUE INDEX `idlands_UNIQUE` (`idlands` ASC),
  INDEX `fk_lands_land_type1_idx` (`land_type_idland_type` ASC),
  INDEX `fk_lands_municipalities1_idx` (`municipalities_idmunicipalities` ASC),
  INDEX `fk_lands_type_of_contract1_idx` (`type_of_contract_idtype_of_contract` ASC),
  INDEX `fk_lands_search_users_users1_idx` (`users_users_id_user` ASC),
  CONSTRAINT `fk_lands_land_type10`
    FOREIGN KEY (`land_type_idland_type`)
    REFERENCES `buscoPiso`.`land_type` (`idland_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lands_municipalities10`
    FOREIGN KEY (`municipalities_idmunicipalities`)
    REFERENCES `buscoPiso`.`municipalities` (`idmunicipalities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lands_type_of_contract10`
    FOREIGN KEY (`type_of_contract_idtype_of_contract`)
    REFERENCES `buscoPiso`.`type_of_contract` (`idtype_of_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lands_search_users_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`users_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`users_images` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`users_images` (
  `idusers_images` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `users_users_id_user` INT NOT NULL,
  PRIMARY KEY (`idusers_images`, `users_users_id_user`),
  INDEX `fk_users_images_users1_idx` (`users_users_id_user` ASC),
  CONSTRAINT `fk_users_images_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`floors_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`floors_images` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`floors_images` (
  `idfloors_images` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `floors_idfloors` INT NOT NULL,
  PRIMARY KEY (`idfloors_images`),
  INDEX `fk_floors_images_floors1_idx` (`floors_idfloors` ASC),
  CONSTRAINT `fk_floors_images_floors1`
    FOREIGN KEY (`floors_idfloors`)
    REFERENCES `buscoPiso`.`floors` (`idfloors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`offices_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`offices_images` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`offices_images` (
  `idoffices_images` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `offices_idoffices` INT NOT NULL,
  PRIMARY KEY (`idoffices_images`),
  INDEX `fk_offices_images_offices1_idx` (`offices_idoffices` ASC),
  CONSTRAINT `fk_offices_images_offices1`
    FOREIGN KEY (`offices_idoffices`)
    REFERENCES `buscoPiso`.`offices` (`idoffices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`garages_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`garages_images` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`garages_images` (
  `idgarages_images` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `garages_idgarages` INT NOT NULL,
  PRIMARY KEY (`idgarages_images`),
  INDEX `fk_garages_images_garages1_idx` (`garages_idgarages` ASC),
  CONSTRAINT `fk_garages_images_garages1`
    FOREIGN KEY (`garages_idgarages`)
    REFERENCES `buscoPiso`.`garages` (`idgarages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`locals_warehouses_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`locals_warehouses_images` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`locals_warehouses_images` (
  `idlocals_warehouses_images` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `locals_warehouses_idlocals_warehouses` INT NOT NULL,
  PRIMARY KEY (`idlocals_warehouses_images`, `locals_warehouses_idlocals_warehouses`),
  INDEX `fk_locals_warehouses_images_locals_warehouses1_idx` (`locals_warehouses_idlocals_warehouses` ASC),
  CONSTRAINT `fk_locals_warehouses_images_locals_warehouses1`
    FOREIGN KEY (`locals_warehouses_idlocals_warehouses`)
    REFERENCES `buscoPiso`.`locals_warehouses` (`idlocals_warehouses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`lands_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`lands_images` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`lands_images` (
  `idlands_images` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `lands_idlands` INT NOT NULL,
  PRIMARY KEY (`idlands_images`, `lands_idlands`),
  INDEX `fk_lands_images_lands1_idx` (`lands_idlands` ASC),
  CONSTRAINT `fk_lands_images_lands1`
    FOREIGN KEY (`lands_idlands`)
    REFERENCES `buscoPiso`.`lands` (`idlands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`chats` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`chats` (
  `idchats` INT NOT NULL,
  `text` TEXT NOT NULL,
  `text_time` TIMESTAMP NOT NULL,
  `users_users_id_user1` INT NOT NULL,
  `users_users_id_user2` INT NOT NULL,
  PRIMARY KEY (`idchats`, `users_users_id_user1`, `users_users_id_user2`),
  INDEX `fk_chats_users2_idx` (`users_users_id_user2` ASC),
  UNIQUE INDEX `idchats_UNIQUE` (`idchats` ASC),
  CONSTRAINT `fk_chats_users1`
    FOREIGN KEY (`users_users_id_user1`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chats_users2`
    FOREIGN KEY (`users_users_id_user2`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`payment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`payment_type` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`payment_type` (
  `idpayment_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `number_of_users` INT NOT NULL,
  PRIMARY KEY (`idpayment_type`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `number_of_users_UNIQUE` (`number_of_users` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`payment_methods` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`payment_methods` (
  `idpayment_methods` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idpayment_methods`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buscoPiso`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `buscoPiso`.`payments` ;

CREATE TABLE IF NOT EXISTS `buscoPiso`.`payments` (
  `idpayments` INT NOT NULL AUTO_INCREMENT,
  `payment_date` DATE NOT NULL,
  `date_of_expiry` DATE NOT NULL,
  `price` DECIMAL NOT NULL,
  `iva` INT NOT NULL,
  `users_users_id_user` INT NULL,
  `business_office_idoffice` INT NULL,
  `payment_type_idpayment_type` INT NOT NULL,
  `payment_methods_idpayment_methods` INT NOT NULL,
  PRIMARY KEY (`idpayments`, `payment_type_idpayment_type`, `payment_methods_idpayment_methods`),
  INDEX `fk_payments_users1_idx` (`users_users_id_user` ASC),
  INDEX `fk_payments_business_office1_idx` (`business_office_idoffice` ASC),
  INDEX `fk_payments_payment_type1_idx` (`payment_type_idpayment_type` ASC),
  INDEX `fk_payments_payment_methods1_idx` (`payment_methods_idpayment_methods` ASC),
  CONSTRAINT `fk_payments_users1`
    FOREIGN KEY (`users_users_id_user`)
    REFERENCES `buscoPiso`.`users` (`users_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_business_office1`
    FOREIGN KEY (`business_office_idoffice`)
    REFERENCES `buscoPiso`.`business_office` (`idoffice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_payment_type1`
    FOREIGN KEY (`payment_type_idpayment_type`)
    REFERENCES `buscoPiso`.`payment_type` (`idpayment_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_payment_methods1`
    FOREIGN KEY (`payment_methods_idpayment_methods`)
    REFERENCES `buscoPiso`.`payment_methods` (`idpayment_methods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
